version: "3.1"

services:
  db:
    container_name: ats-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: D1ymf8wyQEGthFR1E9xhCq
      POSTGRES_USER: LTIdbUser
      POSTGRES_DB: LTIdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    container_name: ats-minio
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API MinIO
      - "9001:9001"  # Console Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  minio-init:
    container_name: ats-minio-init
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/ats-bucket --ignore-existing;
      /usr/bin/mc policy download myminio/ats-bucket;
      exit 0;
      "

  mailpit:
    container_name: ats-mailpit
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"  # SMTP Server
      - "8025:8025"  # Web Interface
    restart: always
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  postgres_data:
  minio_data:
